# Generated by Django 4.2.6 on 2023-10-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='descripton',
            field=models.TextField(blank=True),
        ),
    ]
